# Generated by Django 4.2.3 on 2023-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=60, verbose_name='Покупатель')),
                ('item', models.CharField(max_length=256, verbose_name='Товар')),
                ('total', models.IntegerField(verbose_name='Сумма')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
                ('date', models.DateTimeField(verbose_name='Дата сделки')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ('-date',),
            },
        ),
    ]
