# Generated by Django 4.2.3 on 2023-07-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.UniqueConstraint(fields=('customer', 'date'), name='deal-already-registered'),
        ),
    ]
